version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/

volumes:
  db:
  static:
  media:
