# Generated by Django 4.1.2 on 2022-10-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Категория товара/услуги",
                "verbose_name_plural": "Категории товаров/услуг",
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Район города",
                "verbose_name_plural": "Районы городов",
            },
        ),
        migrations.AlterModelOptions(
            name="networkorganization",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Сеть предприятия",
                "verbose_name_plural": "Сеть предприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Предприятие",
                "verbose_name_plural": "Предприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationdistrict",
            options={
                "verbose_name": "Расположение предприятия",
                "verbose_name_plural": "Расположение предприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Товар/Услуга",
                "verbose_name_plural": "Товары/услуги",
            },
        ),
        migrations.AlterModelOptions(
            name="productorganization",
            options={
                "verbose_name": "Товары предприятия",
                "verbose_name_plural": "Товары предприятий",
            },
        ),
        migrations.AlterField(
            model_name="organization",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="organizations.networkorganization",
                verbose_name="Сеть предприятия",
            ),
        ),
        migrations.AlterField(
            model_name="organizationdistrict",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_districts",
                to="organizations.district",
                verbose_name="Район города",
            ),
        ),
        migrations.AlterField(
            model_name="productorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_organizations",
                to="organizations.organization",
                verbose_name="Предприятие",
            ),
        ),
        migrations.AlterField(
            model_name="productorganization",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="productorganization",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_organizations",
                to="organizations.product",
                verbose_name="Товар/Услуга",
            ),
        ),
    ]
